#!/bin/bash


mysql_root_password=xxxxxxxxxxxxxxxxxxxxxR!23
prestashop_mysql_user_password=vvvvvvvvvvvvvvvvvvvvvvvTra3!

apt update
if [ $? -ne 0 ]; then
	echo "Could not run apt update"
	exit 1
fi


apt upgrade -y
if [ $? -ne 0 ]; then
        echo "Could not run apt upgrade"
        exit 1
fi

apt install nginx -y

if [ $? -ne 0 ]; then
        echo "Could not install nginx"
        exit 1
fi

sudo apt install mysql-server -y

if [ $? -ne 0 ]; then
        echo "Could not install mysql-server"
        exit 1
fi

mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '$mysql_root_password';"
if [ $? -ne 0 ]; then
        echo "Could not alter root user settings"
        exit 1
fi



mysql_secure_installation --password=$mysql_root_password --use-default
if [ $? -ne 0 ]; then
        echo "Could not secure mysql-server"
        exit 1
fi


mysql -u root --password=$mysql_root_password -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;"
if [ $? -ne 0 ]; then
        echo "Could not change the auth type back for root"
        exit 1
fi

SQL1="CREATE DATABASE prestashopdb;"
SQL2="CREATE USER 'prestashop'@'localhost' IDENTIFIED BY '$prestashop_mysql_user_password';"
SQL3="GRANT ALL PRIVILEGES ON prestashopdb.* TO 'prestashop'@'localhost';"
SQL4="FLUSH PRIVILEGES;"

mysql -u root --password=$mysql_root_password -e "$SQL1"
if [ $? -ne 0 ]; then
        echo "Could not create database"
        exit 1
fi

mysql -u root --password=$mysql_root_password -e "$SQL2"
if [ $? -ne 0 ]; then
        echo "Could not create the prestashop db user"
        #exit 1
fi

mysql -u root --password=$mysql_root_password -e "$SQL3"
if [ $? -ne 0 ]; then
        echo "Could not grant privileges to the prestashop db user"
        exit 1
fi

mysql -u root --password=$mysql_root_password -e "$SQL4"
if [ $? -ne 0 ]; then
        echo "Could not flush privileges"
        exit 1
fi



wget https://github.com/PrestaShop/PrestaShop/releases/download/8.1.7/prestashop_8.1.7.zip
if [ $? -ne 0 ]; then
        echo "Could not download the  prestashop zip file"
        exit 1
fi


apt install unzip
if [ $? -ne 0 ]; then
        echo "Could not install unzip"
        exit 1
fi

mkdir temp
if [ $? -ne 0 ]; then
        echo "Could not create temp directory"

        exit 1
fi

unzip prestashop_8.1.7.zip -d temp/
if [ $? -ne 0 ]; then
        echo "Could not unzip prestashop zip file"
        exit 1
fi


cp temp/* /var/www/html

if [ $? -ne 0 ]; then
        echo "Could not copy files to www directory"
        exit 1
fi


apt -y install php php-fpm php-zip php-xml php-curl php-mysql php-gd php-intl php-mbstring
if [ $? -ne 0 ]; then
        echo "Could not install php"
        exit 1
fi

chown -R www-data:www-data /var/www/html
if [ $? -ne 0 ]; then
        echo "Could not change owner on files"
        exit 1
fi

find /var/www/html -type d -exec chmod 755 {} ";"
if [ $? -ne 0 ]; then
        echo "Could not set permissions on directories"
        exit 1
fi


find /var/www/html -type f -exec chmod 644 {} ";"
if [ $? -ne 0 ]; then
        echo "Could not set permissions on files"
        exit 1
fi

cp default /etc/nginx/sites-available/
chmod 644 /etc/nginx/sites-available/default
if [ $? -ne 0 ]; then
        echo "Could not set permissions on default file"
        exit 1
fi



rm -r temp/
rm prestashop_8.1.7.zip

exit 0


